apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-gateway-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"  # Redirect HTTP to HTTPS
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"  # Force redirect to HTTPS
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.localhost
      secretName: tls-secret  # Reference to the TLS secret created in Kubernetes
  rules:
    - host: "api.localhost"
      http:
        paths:
          - path: /api-1
            pathType: Prefix
            backend:
              service:
                name: api-1-service
                port:
                  number: 3000
          - path: /api-2
            pathType: Prefix
            backend:
              service:
                name: api-2-service
                port:
                  number: 3001
          - path: /auth-api
            pathType: Prefix
            backend:
              service:
                name: auth-api-service
                port:
                  number: 3002
