apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-gateway-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: "api.rules-engine.localhost"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rules-engine-api-service
            port:
              number: 3000
