# Define a local command to create the TLS secret if it doesn't exist
local('kubectl create secret tls keycloak-tls-secret --cert=../../local-config/keycloak.localhost.pem --key=../../local-config/keycloak.localhost-key.pem || true')

# Load Keycloak Kubernetes config
k8s_yaml([
    './deployment.yaml', 
    './service.yaml', 
    './ingress.yaml', 
    './pvc.yaml'
])

# Define Kubernetes resource
k8s_resource('keycloak')
