apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-2
  template:
    metadata:
      labels:
        app: api-2
    spec:
      containers:
      - name: api-2
        image: api-2:latest
        imagePullPolicy: IfNotPresent  # defaults to local image
        ports:
        - containerPort: 3001
        resources:
          requests:
            memory: "256Mi"  # Minimum memory guaranteed for NestJS
            cpu: "500m"      # Minimum CPU guaranteed (50% of a core)
          limits:
            memory: "512Mi"  # Maximum memory allowed for NestJS
            cpu: "1000m"     # Maximum CPU allowed (1 full core)
