apiVersion: v1
kind: Service
metadata:
  name: api-2-service
spec:
  type: ClusterIP  # Ensures it's accessible within the cluster
  selector:
    app: api-2
  ports:
    - port: 3001       # The port the service exposes
      targetPort: 3001  # The port the NestJS app is listening on
