apiVersion: apps/v1
kind: Deployment
metadata:
  name: rules-engine-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rules-engine-ui
  template:
    metadata:
      labels:
        app: rules-engine-ui
    spec:
      containers:
      - name: rules-engine-ui
        image: rules-engine-ui:latest
        imagePullPolicy: IfNotPresent # Defaults to local image
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "256Mi"    # Minimum memory guaranteed for the container
            cpu: "500m"        # Minimum CPU guaranteed for the container
          limits:
            memory: "512Mi"    # Maximum memory allowed for the container
            cpu: "1000m"       # Maximum CPU allowed for the container (1 full core)