# Load Keycloak configuration
include('./keycloak/Tiltfile')

# Load Angular apps
include('./angular/web-app-1/Tiltfile')
include('./angular/web-app-2/Tiltfile')

# Load common configuration
include('./common/Tiltfile')

# Load NestJS APIs
include('./nestjs/api-1/Tiltfile')
include('./nestjs/api-2/Tiltfile')
include('./nestjs/auth-api/Tiltfile')
