apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-keycloak-instance-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
