# Load the Kubernetes config
k8s_yaml('./deployment.yaml')
k8s_yaml('./service.yaml')
k8s_yaml('./pvc.yaml')

# Build the container
docker_build('postgres-keycloak-instance', '../../../../databases/postgres/keycloak-instance')

# Deploy the resources to Kubernetes
k8s_resource('postgres-keycloak-instance', port_forwards=5433)
