apiVersion: v1
kind: Service
metadata:
  name: api-1-service
spec:
  type: ClusterIP  # Ensures it's accessible within the cluster
  selector:
    app: api-1
  ports:
    - port: 3000       # The port the service exposes
      targetPort: 3000  # The port the NestJS app is listening on
